---
- hosts: neo4j-cluster
  vars:
    new_heap_initial_size: 31g
    new_heap_max_size: 31g
    new_pagecache_size: 194000m
    new_minimum_core_cluster_size_at_formation: 5
    new_minimum_core_cluster_size_at_runtime: 5
    new_initial_discovery_members: 10.162.20.224:5000,10.162.60.168:5000
    host_ip_address: 10.162.111.206
  tasks:  
    - name: Install Java
      check_mode: yes
      apt:
        name: openjdk-8-jre-headless
        update-cache: yes
      become: yes
    - name: Install Neo4j Enterprise
      check_mode: yes
      shell: |
        wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
        echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
        sudo apt-get update        
        echo "neo4j-enterprise neo4j/question select I ACCEPT" | sudo debconf-set-selections
        echo "neo4j-enterprise neo4j/license note" | sudo debconf-set-selections
        sudo apt-get install -y neo4j-enterprise=1:3.4.10
      become: yes
    - name: Start Neo4j Service
      check_mode: yes
      shell: |
        service neo4j start
      become: yes
    - name: Stop Neo4j Service
      check_mode: no
      shell: |
        service neo4j stop
      become: yes
    - name: Stop Neo4j Service
      check_mode: yes
      shell: |
        sudo poweroff
    - name: Inital memory and network configuration (neo4j.conf)
      check_mode: yes
      shell: |
        sed -i -e '/#dbms.memory.heap.initial_size=/ s/#dbms.memory.heap.initial_size=.*/dbms.memory.heap.initial_size={{new_heap_initial_size}}/' /etc/neo4j/neo4j.conf
        sed -i -e '/#dbms.memory.heap.max_size=/ s/#dbms.memory.heap.max_size=.*/dbms.memory.heap.max_size={{new_heap_max_size}}/' /etc/neo4j/neo4j.conf
        sed -i -e '/#dbms.memory.pagecache.size=/ s/#dbms.memory.pagecache.size=.*/dbms.memory.pagecache.size={{new_pagecache_size}}/' /etc/neo4j/neo4j.conf        
        sed -i -e '/#dbms.connectors.default_listen_address=/ s/#dbms.connectors.default_listen_address=.*/dbms.connectors.default_listen_address=0.0.0.0/' /etc/neo4j/neo4j.conf
        sed -i -e "/#dbms.connectors.default_advertised_address=/ s/#dbms.connectors.default_advertised_address=.*/dbms.connectors.default_advertised_address==$(hostname -I)/" /etc/neo4j/neo4j.conf        
      become: yes
    - name: Inital cluster configuration (neo4j.conf) for core server(s)
      check_mode: yes
      shell: |
        sed -i -e '/#dbms.mode=/ s/#dbms.mode=.*/dbms.mode=CORE/' /etc/neo4j/neo4j.conf
        sed -i -e '/#causal_clustering.minimum_core_cluster_size_at_formation=/ s/#causal_clustering.minimum_core_cluster_size_at_formation=.*/causal_clustering.minimum_core_cluster_size_at_formation={{new_minimum_core_cluster_size_at_formation}}/' /etc/neo4j/neo4j.conf
        sed -i -e '/#causal_clustering.minimum_core_cluster_size_at_runtime=/ s/#causal_clustering.minimum_core_cluster_size_at_runtime.*/causal_clustering.minimum_core_cluster_size_at_runtime={{new_minimum_core_cluster_size_at_runtime}}/' /etc/neo4j/neo4j.conf
        sed -i -e '/#causal_clustering.initial_discovery_members/ s/#causal_clustering.initial_discovery_members.*/causal_clustering.initial_discovery_members={{new_initial_discovery_members}}/' /etc/neo4j/neo4j.conf
      become: yes
    - name: Inital cluster configuration (neo4j.conf) for read replica(s)
      check_mode: yes
      shell: |
        sed -i -e '/#dbms.mode=/ s/#dbms.mode=.*/dbms.mode=READ_REPLICA/' /etc/neo4j/neo4j.conf
        sed -i -e '/#causal_clustering.initial_discovery_members/ s/#causal_clustering.initial_discovery_members.*/causal_clustering.initial_discovery_members={{new_initial_discovery_members}}/' /etc/neo4j/neo4j.conf
      become: yes
    - name: Update memory configuration (neo4j.conf) for all nodes in the cluster
      check_mode: yes
      shell: |
        sed -i -e '/dbms.memory.pagecache.size=/ s/=.*/={{new_heap_initial_size}}/' /etc/neo4j/neo4j.conf
        sed -i -e '/dbms.memory.pagecache.size=/ s/=.*/={{new_heap_max_size}}/' /etc/neo4j/neo4j.conf
        sed -i -e '/dbms.memory.pagecache.size=/ s/=.*/={{new_pagecache_size}}/' /etc/neo4j/neo4j.conf
      become: yes
    - name: Copy graph.db      
      check_mode: yes
      become_user: neo-01
      shell: |        
        scp -r neo-01@{{host_ip_address}}:/home/neo-01/graph.db .
    - name: Configure graph.db
      check_mode: yes
      become: yes
      shell: |
        cd /home/neo-01/
        service neo4j stop
        cp -r /home/neo-01/graph.db /var/lib/neo4j/data/databases/
        chown -R neo4j:neo4j /var/lib/neo4j/data/databases/graph.db        
...
